Code to bomb the world
DOMINION-JOHN1/python-challenge pull request #1
Opened 2023-04-15 08:48 UTC by DOMINION-JOHN1

2023-04-15 08:52 UTC, greatertomi requested changes

2023-04-15 08:52 UTC, greatertomi commented on challenge21.py
> +print("Bomb the world")
Save the world

2023-04-15 08:52 UTC, greatertomi requested changes

2023-04-15 08:52 UTC, greatertomi commented on challenge21.py
> +print("Bomb the world")
```suggestion
print("Save the world")
```

2023-04-15 09:03 UTC, greatertomi approved these changes

2023-04-15 09:03 UTC, merged

2023-04-18 19:02 UTC, DOMINION-JOHN1 commented
I will bomb both this world and its solar system